// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1WrRGNARU2jAtNeZUVQMlXq0uM93Q1mg',
    appId: '1:214070854247:web:156b549fa52fe1dc62cac2',
    messagingSenderId: '214070854247',
    projectId: 'camera-store-24',
    authDomain: 'camera-store-24.firebaseapp.com',
    storageBucket: 'camera-store-24.firebasestorage.app',
    measurementId: 'G-GJS5CS6540',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzgeS-CD-g5ZntZOpfuxjGUUyK34c_l3Q',
    appId: '1:214070854247:android:b61c4d3f3c0f269f62cac2',
    messagingSenderId: '214070854247',
    projectId: 'camera-store-24',
    storageBucket: 'camera-store-24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpaLJdBcq8tjz4AXlo4biTwCeVduCP_iI',
    appId: '1:214070854247:ios:8a1937809581f42662cac2',
    messagingSenderId: '214070854247',
    projectId: 'camera-store-24',
    storageBucket: 'camera-store-24.firebasestorage.app',
    iosBundleId: 'com.example.pixellens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpaLJdBcq8tjz4AXlo4biTwCeVduCP_iI',
    appId: '1:214070854247:ios:8a1937809581f42662cac2',
    messagingSenderId: '214070854247',
    projectId: 'camera-store-24',
    storageBucket: 'camera-store-24.firebasestorage.app',
    iosBundleId: 'com.example.pixellens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1WrRGNARU2jAtNeZUVQMlXq0uM93Q1mg',
    appId: '1:214070854247:web:33fdd51b7ca7651c62cac2',
    messagingSenderId: '214070854247',
    projectId: 'camera-store-24',
    authDomain: 'camera-store-24.firebaseapp.com',
    storageBucket: 'camera-store-24.firebasestorage.app',
    measurementId: 'G-4B9ZQ556ZH',
  );
}
